project         = "demo2"
environment     = "dev"
github_repo     = "ugalileo-pdds-oyd-2026/session-8-demo-2-secrets-oidc-tls"
db_username     = "appuser"
domain_name     = "app.demo.oyd.solid.com.gt"
route53_zone_id = "Z04898973RR9YTYU300U1"
